* A-world
** ??

*** ??

- 3x3: Elder Tannhaus’ father has the POCKETWATCH.

** 1888

*** June 27

- (2x8): JONAS-17, FRANZISKA-4, MAGNUS-4 and BARTOSZ-5 arrive from the
  apocalypse in 2020 with the MACHINE.  They are out of fuel.

*** September 21

- 3x2: MARTHA-Xb arrives from world B after having brought JONAS-9b
  there.  She finds JONAS-Y busy at work trying to build a time
  machine.  He is shocked to find her alive, because he is the future
  version of JONAS-9, who was not rescued by MARTHA-Xb at the
  apocalypse, and who doesn’t know of world B.  She’s there to help
  him find the ORIGIN.

*** September 22

- 3x2: MARTHA-Xb wakes, finding JONAS-Y there holding the letter,
  supposedly from MARTHA, that was given to him by NOAH-2 on June
  27, 2020.  Downstairs she finds the nascent Sic Mundus, consisting
  of JONAS-Y, FRANZISKA-4, MAGNUS-4 and BARTOSZ-5.  None of them
  really understand what to make of her.  She intends to make
  everything right, so that nobody die in either world.

- 3x2: MARTHA-Xb explains the parallel world concept to Sic Mundus.
  JONAS-Y demands to know how she found them.  She says that JONAS
  told her.  (That would be JONAS-9b or one of his future versions.)
  JONAS-Y questions her motives.

- 3x2: BARTOSZ-5 confides in MARTHA-Xb, saying that JONAS-Y has begun
  changing after they arrived in 1888.  He shows her the Sic Mundus
  headquarters.  Old Tannhaus is the only remaining member of the old
  Sic Mundus, which is now being co-opted by JONAS-Y, trying to
  rebuild things by memory after seeing them in 1921.  MARTHA-Xb tells
  him that ADAM and JONAS are the same person.

*** September 23

- 3x3: Elder Tannhaus still has the pocketwatch.  UNKNOWN arrives to
  murder him, to prevent him from announcing the existence of Sic
  Mundus to the world at large.  They take a copy of the play Ariadne.

- 3x3: BARTOSZ-5 accuses JONAS-Y of knowing that they would all get
  stuck in 1888.  JONAS-Y retorts that MARTHA-Xb is using him, that
  the real MARTHA is dead.  BARTOSZ-5 tries to force JONAS-Y to admit
  that he is ADAM, and that it was really his future self who killed
  MARTHA-3.  It develops into a fight and BARTOSZ-5 shouts the secret
  out loud.

- 3x3: MARTHA-Xb has the MEDALLION.  It must be chronologically the
  same as the one that MARTHA-Zb shows JONAS-9b on November 5, 2019,
  in world B.

- 3x3: JONAS-Y asks MARTHA-Xb why he can’t remember that he went to
  her world.  She doesn’t understand it either.  She says she didn’t
  write the NOTE.  Old Tannhaus founded Sic Mundus when trying to
  bring his wife back to life.  MARTHA-Xb wants to save everyone who
  is dead in her world, and wants to prove to JONAS-Y that she can be
  trusted.  She shows him her ORB and gives him her last remaining
  capsuel of GOD-PARTICLE mass.  (She actually has another.)

- 3x3: JONAS-Y is temporarily able to activate the GOD-PARTICLE mass,
  but his machine isn’t fully functional yet, so it doesn’t last long.
  During this, MARTHA-Xb has snuck off to her room, where she uses
  another GOD-PARTICLE capsule and the ORB to travel to 2053.

*** September 24

- 3x6: JONAS-Y burns the NOTE.

- 3x6: MARTHA-Yb is seen traveling from world B on some mission for
  Erit Lux.  She places the NOTE for JONAS-Y, as well as the
  POCKETWATCH.

** 1890

- 3x7: Experimenting with the GOD-PARTICLE mass, JONAS-Y sustains an
  injury to his upper right arm.  BARTOSZ-5 questions the progress of
  the work, questioning whether JONAS-Y really wants to end the
  apocalypse.  He is right: JONAS-Y wants to end the origin, achieving
  paradise.  BARTOSZ-5 just wants to leave.

- 3x7: In the forest, BARTOSZ-5 runs into SILJA-X, who has traveled
  from 2053 under the orders of JONAS-Z.

** 1904

*** ??

- 3x7: SILJA-X, having made her life in this time together with
  BARTOSZ-5, gives birth to a baby boy: NOAH-1, although they name him
  Hanno.

** 1910

*** ???

- 3x7: SILJA-X dies in childbirth, giving birth to AGNES-1.

** 1911

*** ??

- 3x7: While fixing a car, BARTOSZ-5 is approached by HANNAH-5, with
  young SILJA-1 by her side, already with the scar.  HANNAH-5 is
  looking for JONAS-Y, but BARTOSZ-5 warns her he’s changed.  He takes
  them to the Sic Mundus headquarters, now fully furnished as we know
  it, and JONAS-Y has fully absorbed the ADAM persona and look.  She
  tells him that MARTHA-Zb (EVA) helped her there, immediately raising
  JONAS-Y’s suspicions.

- 3x7: HANNA-5 is murdered in her bed by JONAS-Y, with SILJA-1
  sleeping nearby.  He takes custody of SILJA-1 intending to send her
  to the far future “where she belongs”.

** 1920

*** ??

- 3x7: NOAH-3, having made his way back to his native time, meets his
  younger self, NOAH-1, working at an inn.

- 3x7: NOAH-3 arrives back at the Sic Mundus headquarters.  JONAS-Z
  tells him that his younger self (JONAS-9) really didn’t take
  CHARLOTTE-1.  Instead JONAS-Z turns his suspicion toward CLAUDIA.
  NOAH-3 has the NOTEBOOK with the last pages missing, as JONAS-Z
  expected.  JONAS-Z tasks NOAH-3 to find them, as they will lead him
  to CHARLOTTE and paradise.  It’s at this point that NOAH-3 becomes
  the priest of Winden, at age 42 according to the newspaper.

** 1921

*** January 8

- 2x1: A photo is taken of the members of Sic Mundus.  It eventually
  ends up in the hands of TANNHAUS the younger.  In it can be seen
  MAGNUS-2, FRANZISKA-2, JONAS-Z, NOAH-1 and NOAH-Y, as well as
  several others.

*** June 21

- 2x1: NOAH-1 and another man are digging the passage for Sic Mundus.
  NOAH-1 kills the other man when he finds that he has lost his faith
  in their mission.  The other man has waited for his death and thinks
  it’s interesting that it will be NOAH-1 who kills him.  He hopes
  that one day, NOAH-1 will lose faith in JONAS-Z.  (That day will
  come.)

- 2x1: NOAH-Y is comforting NOAH-1, who has just made his “first step”
  (killed a man).  He explains that some things are still kept from
  his younger self.

- 2x1: JONAS-Z and NOAH-Y are discussing the NOTEBOOK.  They want to
  find the missing pages.  FRANZISKA-2 arrives to tell JONAS-Z that
  some people are waiting for him.  NOAH-Y appears to have a MACHINE.
  He is probably about to travel to 2020.

*** June 23

- 2x3: NOAH-Y returns using the MACHINE after killing CLAUDIA-Z
  in 1954.  He hides the existence of the last pages from JONAS-Z.
  JONAS-Z may have been using NOAH-Y’s hatred for CLAUDIA-Z to control
  him, and NOAH-Y may now be disillusioned.

*** June 24

- 2x4: JONAS-6 arrives from the distant future, having spent months in
  the 2050s trying to get the GOD-PARTICLE mass to work.  He has a bad
  scar around his neck.  He meets AGNES-X and NOAH-1 at the inn where
  he takes a room.

- 2x4: When JONAS-6 wakes up, NOAH-1 appears to know about him, and
  having expected his arrival for quite a while.  JONAS-6 goes to the
  caves, hoping to travel to 2020 to prevent the apocalypse, but finds
  the passage still unfinished.

- 2x4: NOAH-1 says the passage will not open for another 32 years (in
  1953, exactly 33 years before the incident on the power plant in
  1986).  He takes JONAS-6 to Sic Mundus.  He is met by NOAH-Y.
  They’ve met before (when they abducted JONAS in 1986 to lock him in
  the BUNKER, I guess).

- 2x4: NOAH-1 asks how the prophecy came to be, and who wrote the
  book.  They don’t know.  (It was UNKNOWN.)  They intend to set
  JONAS-6 on a path that will start the last cycle.

- 2x4: In JONAS-Z’s Sic Mundus office, the painting is The Fall of the
  Damned by Rubens.  JONAS-Z reveals himself to JONAS-6 as his own
  elder self.  JONAS-6 wants to end time travel shenanigans, and save
  people from the apocalypse, but JONAS-Z wants to end the world.

*** June 25

- 2x5: JONAS-6 wakes up, and JONAS-Z asks him to dress in the yellow
  jacket, which JONAS-6 had hidden on arriving in 1921.

- 2x5: JONAS-Z tells the story about loss of naivete, innocence and
  life.  Does that have anything to do with the three ages of every
  character?

- 2x5: JONAS-Z says he has discovered a “loophole” to exit the loop.
  They want to create a new world without time, without God.  JONAS-Z
  has lived his entire life trying to avoid this exact conversation,
  but not claims to understand.

- 2x5: JONAS-6 asks why, if there is a loophole, has JONAS-Z not used
  it to change anything.  JONAS-Z says there is a sequence of
  development that must be taken, and JONAS-6 is only a link.  The
  camera shows technical drawings of the chair, the MACHINE, and other
  devices.

- 2x5: Finally, JONAS-6 is taken to the GOD-PARTICLE mass.  The future
  mass was created by the apocalypse.  This one was created by Sic
  Mundus.  JONAS-Z sends JONAS-6 to June 20, 2019, becoming JONAS-7.
  JONAS-6 intends to prevent his father from committing suicide, but
  JONAS-Z knows that he will merely make it happen in the first place.
  This is the first time we see someone traveling by an offset that is
  not a multiple of 33 years.  Something about the device Sic Mundus
  is using makes that possible

- 2x6: JONAS-Z has the MEDALLION.  MAGNUS-Y expresses some
  dissatisfaction to JONAS-Z, but FRANZISKA-Y says they must all make
  some sacrifices.

*** June 27

- 2x8: NOAH-Y is unable to tell NOAH-1 about CHARLOTTE’s identity, or
  he would not follow the path needed to become who he is today.
  MAGNUS-Y and FRANZISKA-Y arrive.  Everything is prepared.  NOAH-1 is
  taken away to travel to the future, to play his role in the
  apocalypse in 2020, becoming NOAH-2.

- 2x8: NOAH-Y confronts JONAS-Z about his lies.  He throws the last
  pages of the NOTEBOOK at him.  JONAS-Z says that CLAUDIA was right:
  NOAH-Y doesn’t understand how the game is played.  (When did
  CLAUDIA say this?)  NOAH-Y is unable to kill JONAS-Z, as he believes
  he must.  FRANZISKA-Y, MAGNUS-Y and AGNES-Y arrive.  AGNES-Y uses
  the same gun to kill NOAH-Y that could not kill JONAS-Z.

- 2x8: After having sent NOAH-1 to 2020, JONAS-Z follows suit.

- 2x8: At the time of the apocalypse, FRANZISKA-Y and MAGNUS-Y are
  manipulating the large time travel device.  Are they influencing
  events?  MAGNUS-Y and AGNES-Y are next seen in 2053.  It’s unclear
  when or exactly how they traveled there.

** ??

*** ??

- 3x1: At some point, UNKNOWN enters the Sic Mundus headquarters,
  which have been abandoned for some time, and burns it down.

** 1953

*** ??

- ??: In the summer of 1953, the passage to 1986 and 2019 opens in the
  caves, because of an incident in the power plant’s volume control
  system in 1986.

*** November 5

- 1x2: HELGE-Y drags the dead body of ERIK-3 through the forest.

*** November 9

- 1x7: HELGE-Y and NOAH-Y clean up the dead body of YASIN-3, who has
  died in the time travel experiments.  NOAH-Y writes the date on the
  wall of the BUNKER.  The date of ERIK-3’s death is already there.

*** November 10

- 1x8: EGON is on site as two dead bodies are discovered at the power
  plant construction site.  They are ERIK-3 and YASIN-3.  They are
  wearing futuristic clothing and have PENNIES from 1986.

- 1x8: HELGE-1 plays in the bunker and notices NOAH-Y’s writing on the
  wall.

- 1x8: ULRICH-2 arrives from 2019, meets young HELGE-1 (not knowing
  who he is) being bullied, scares away the bullies and teaches him to
  bite.

- 1x8: On his way to Winden, ULRICH-2 meets AGNES-Y and TRONTE-1, his
  grandmother and father.  They are in the process of moving there.

- 1x8: ULRICH-2 meets TANNHAUS and shows him the BOOK that he has yet
  to write, which ULRICH-2 got from HELGE-Z.

- 1x8: While HELGE-1 is being tutored by CLAUDIA-1, AGNES-Y and
  TRONTE-1 arrive at the Tiedemann home to rent a room.  DORIS is
  there to receive them.  AGNES-Y says her husband is dead.  AGNES-Y
  will eventually cause the dissolution of EGON and DORIS’ marriage.

- 1x8: INES comes together with JANA to TANNHAUS to pick up a watch,
  and lets slip that two dead children have been found.  ULRICH-2,
  overhearing this and concerned that one of them may be his son,
  leaves in distress, forgetting his jacket, with his PHONE and the
  copy of the BOOK, that TANNHAUS will later use to copy from.

- 1x8: CLAUDIA-1 and HELGE-1 shows TRONTE the caves.  CLAUDIA-1 is
  rude to HELGE-1 (she has taken a liking to TRONTE).  As revenge,
  HELGE-1 causes GRETCHEN-1 the dog to get lost in the caves.  She
  eventually travels to 1986, becoming GRETCHEN-2.

- 1x8: ULRICH-2, believing that killing HELGE-1 will prevent the
  murders, attacks and disfigures him, but fails to kill him.  He
  locks the unconscious HELGE-1 in the BUNKER.

- 1x9: GRETA confesses to NOAH-Y that she never wanted HELGE, and that
  BERND may not be his father.

- 1x9: On his way to the caves, ULRICH-2 is arrested by EGON.
  ULRICH-2 learns that he didn’t change the course of time.

- 1x9: In the BUNKER, HELGE-1 wakes up.

*** November 11

- 1x9: CLAUDIA-Z visits TANNHAUS and gives him the MACHINE BLUEPRINTS,
  asking him to build it.

*** November 12

- 1x10: Under interrogation, ULRICH-2 tells EGON that his wife will
  leave him eventually, and that EGON will start drinking.

- 1x10: JONAS-Y activates the MACHINE in the passage, closing it.
  Lights flicker everywhere.  HELGE-1, having been in the BUNKER for
  two days, sees JONAS-5 in a wormhole.  When they touch he is
  transported to 1986.

** 1954

*** June 23

- 2x3: HELGE-3 arrives from 1954 by the time travel chair.  He refuses
  to speak.

- 2x3: AGNES-Y goes to see CLAUDIA-Z in the bunker.  CLAUDIA-Z
  explains that HELGE-3 was sent back today, and that NOAH-Y is also
  back.  CLAUDIA-Z gives AGNES a paper clipping and instructs her to
  give it back to her (presumably her younger self) later today.
  CLAUDIA-Z is preparing for her death.

- (2x3): At this point, CLAUDIA-Z probably has buried the time machine
  where CLAUDIA-1 will find it 33 years later.

- 2x3: EGON goes to see ULRICH-2, who is in a straitjacket, and tells
  him that HELGE-3 is back.

- 2x3: NOAH-Y gets HELGE-3, who knows NOAH-Y well from the last
  months, to talk.  NOAH-Y has recently traveled from 1987 using the
  MACHINE.

- 2x3: In the church, NOAH-Y finds AGNES-Y.  She has apparently
  deserted Sic Mundus earlier.  She tells him she knows the location
  of the remaining pages, and shows NOAH-Y the newspaper clipping that
  CLAUDIA-Z gave her.  AGNES wants to return to Sic Mundus before the
  new cycle begins.  NOAH-Y hates CLAUDIA.

- 2x3: CLAUDIA-Z goes to see EGON, her father, to apologize (for
  causing his death, in 1987).  When EGON comes home, CLAUDIA-1
  repeats some of the words to him.

- 2x3: CLAUDIA-Z goes to TANNHAUS.  The machine is not yet ready, and
  she tells him it will be 33 more years.  She gives him the BOOK,
  which he has seen before (from ULRICH-2).  She tells him that he
  must tell her how the MACHINE works (in 1987), and he protests that
  he doesn’t know.  CLAUDIA-Z answers that he himself (in 1987) told
  her that someone else (JONAS-Y) told it to him.

- 2x3: NOAH-Y finds CLAUDIA-Z.  He says that she took everything from
  him (CHARLOTTE-1) and that AGNES-Y betrayed her.  CLAUDIA-Z says she
  knew she was going to die, and suggests that NOAH-Y still doesn’t
  know how to play the game.  NOAH-Y believes he is being manipulated.
  He kills her and takes the last pages of the NOTEBOOK, but something
  in it shocks him (presumably about the identity and/or fate of his
  daughter).

- 2x3: We see AGNES holding the newspaper clipping.  It’s a
  description of an unknown woman (CLAUDIA-Z) found dead in the woods.
  Shortly after this, AGNES and NOAH-Y go missing from this timeline.

*** June 26

- 2x7: EGON inspects the dead body of CLAUDIA-Z, recalling that she
  came to see him in the police station.  They suspect she may have
  something to do with HELGE-1’s disappearance.  Her body is full of
  radiation.

- 2x7: HELGE-X does not recognize CLAUDIA-Z from the photo, but he
  says that “he” (NOAH-Y) told him about her.  She is The White Devil,
  and NOAH-Y told him that she wants to kill everyone.

- 2x7: HANNAH-4 arrives from 2020 using the MACHINE.  She wants to see
  ULRICH-2, claiming potentially to be his wife.  She gives her name
  as Katharina Nielsen.

- 2x7: Upon meeting ULRICH-2, HANNAH-4 asks him to say he loves her,
  and not KATHARINA.  He does, but HANNAH-4 still claims she doesn’t
  know him, effectively condemning him to life in prison.

- 2x7: Back in the office, HANNAH-4 begins making moves on EGON.

*** June 27

- 2x8: In 1987, JONAS-8 reopens the passage.

*** September 24

- 3x4: UNKNOWN comes to visit TRONTE in front of the caves.  He talks
  about her mother (AGNES).  TRONTE takes after her.  UNKNOWN gave him
  his name.  (He is is father.)  He gives him the BRACELET, saying it
  used to belong to his mother.  Later that day he gives it to JANA.
  This is the day that the emnity between CLAUDIA-1 and JANA really
  begins.

- 3x4: HANNAH-4’s relationship with EGON is developing well.  He gives
  her a MEDALLION.  HANNAH-4 doesn’t feel well.  She is pregnant, as
  she will find out when she visits the doctor on the same day.

- 3x4: During a conversation between INES, CLAUDIA-1 and JANA, we
  learn that AGNES is missing.  She was last seen by us in the 50s on
  June 25.

- 3x4: DORIS gives EGON a handkerchief she found among AGNES’ things
  with “H.T.” embroidered on it.  She said that her husband was in the
  church, and the name of the priest (NOAH-Y) who disappeared around
  the same time was Hanno Tauber.  All of this is correct, except NOAH
  is not AGNES’ husband, but her brother.  EGON is dismissive and
  DORIS, losing her patience with her husband, erupts in anger.

- 3x4: The investigation into HELGE’s disappearance has stalled.
  GERDA is concerned that Winden is currently without a priest.  She
  wants NOAH-Y found.

- 3x4: DORIS goes to the church to inquire about AGNES and her
  husband, who she believes to be in the church.  She finds UNKNOWN
  there (who is, indeed, the “husband”).  He sees through her, that
  DORIS is more concerned with AGNES than with TRONTE.  He steers the
  conversation in a direction that gets DORIS to divorce EGON.

- 3x4: In the mansion, BERND is furious that his power plant
  construction permit is still not approved.

- 3x4: Outside the town hall, UNKNOWN threatens the mayor to approve
  the power plant construction permit.

- 3x4: EGON gives HANNAH-4 the location of a place where she can get
  an abortion.  When he comes home, DORIS, influenced by UNKNOWN,
  tells him she wants a divorce.

- 3x4: HANNAH-4, at the abortion place, runs into HELENE.  She gives
  her name as KATHARINA, which HELENE likes (she will name her future
  daughter that).  When HELENE enters, HANNAH-4 leaves behind her
  MEDALLION for her, and leaves, still pregnant.  Later, she is
  collected by MARTHA-Zb who helps her and her daughter SILJA-1 travel
  to 1911, to be reunited with JONAS-Y.

** 1986

*** June 21

- 3x8: JONAS-10c and MARTHA-4c arrive from November 8, 2019 in world
  A.  JONAS-10c tells her about the proposed dissolution of the knot.
  They enter the cave, awaiting the opening of the passage.

- 1x9: In the summer of 1986, an incident occurs in the power plant’s
  volume control system, causing a leak of radioactive materials.  At
  BERND’s orders, they are stored in BARRELS in the cave.  The
  incident opens the passage between 1953, 1986 and 2019.

*** ??

- 1x5: At some point, REGINA is tied to a tree by ULRICH-1 and
  KATHARINA-1 as part of some kind of game.  She begins developing
  hatred for both of them.  It’s not clear whether this happens before
  or after the power plant incident, but we can assume that it is
  after based on the haunting sound from the cave.

*** October 9

- REGINA, being afraid after the previous events, is followed home by
  MADS-1.  Later that night, on his way home through the forest,
  MADS-1 goes missing, taken by HELGE-Y and NOAH-Y.

*** November 4

- (1x1): HELGE-Y travels to 2019.

- (1x1): HELGE-Y returns.

- 1x1: ERIK-2 is strapped into the chair in the BUNKER.  Around his
  neck is hung a 1986 PENNY.

*** November 5:

- 1x2, 1x3: MIKKEL-2 arrives, meeting the young versions of many
  adults from 2019.

- 1x3: HELGE-Y gives CLAUDIA-1 the BOOK.

- 1x3: EGON investigates dead sheep, caused by the time travel
  experiments in the BUNKER.  CHARLOTTE-2 also finds dead birds.

- 1x3: MIKKEL-2 meets EGON while looking for his father.  EGON is
  convinved it’s a prank, but he calls the hospital anyway.  INES
  comes to take care of him.

- 1x3: CLAUDIA-1 meets TRONTE.  They have had an affair.

- 1x3: EGON confronts ULRICH-1 about what he believes is a prank.
  ULRICH-1 is listening to the lyrics about taking many lives.

- 1x3: CLAUDIA-1 confronts BERND about discrepancies at the power
  plant.  Something happened a few months ago, which was kept secret
  because the Chernobyl accident has changed public perception about
  nuclear power.  BERND shows her the BARRELS stashed in the cave.

- (1x2): HELGE-Y travels to 2019.

- (1x2): ERIK-2 dies while traveling to 1953.

- 1x3: HANNAH-1 and ULRICH-1 meet at a bus stop.  They talk about
  wishing for a world without Winden.

- 1x3: MIKKEL-2 escapes from the hospital, trying to go back through
  the cave.  He can hear ULRICH-1 in 2019.

- 1x3: TANNHAUS is working on the MACHINE.  It seems he has it working
  for the first time.

*** November 7

- (1x4): At some point, YASIN-2 arrives from 2019, kidnapped.

- 1x5: INES gives MIKKEL-2 a book titled “I am not afraid”.

- 1x5: NOAH-Y visits MIKKEL-2 in the hospital.

- 1x5: HANNAH-1, in love with ULRICH-1, realizes that he is falling
  for KATHARINA-1 instead.  She begins developing a life-long
  animosity against her.  ULRICH-1 and KATHARINA-1 plan to have sex.

- 1x5: HANNAH-1 and MIKKEL-2 meet.  She takes a liking to him, but her
  obsession with ULRICH-1 has already gone too far.  ULRICH-1 and
  KATHARINA-1 have sex.  HANNAH-1 sees them and lies to the police,
  claiming she saw rape.  EGON arrests ULRICH-1.

- 1x5: JONAS-11 arrives from 2019 with the broken MACHINE, and meets
  TANNHAUS in his shop, intending to learn time travel theory from the
  master himself.

*** November 8

- 1x6: JONAS-2 arrives from 2019.  He meets HANNAH-1 and her father
  (his grandfather).  He has the LAMP, the GEIGER COUNTER and the
  LETTER with him.  He sleeps in a watchtover.

*** November 9

- 1x7: EGON asks HELGE-Y about his choice of road home the day MADS-1
  disappeared.  They schedule an interview for the morning of
  November 11.

- 1x7: EGON meets JONAS-2 on the road to the hospital and gives him a
  lift.

- 1x7: JONAS-11 intercepts JONAS-2 before he can try to recover
  MIKKEL-2, warning him that he must now be allowed to live his life
  in the 80s in order for JONAS-2 to live.  Later, JONAS-2 finally
  decides not to interfere.

- 1x7: KATHARINA-1 tells EGON that ULRICH-1 did not rape her.  Her
  injuries are in fact from her mother, HELENE, although she conceals
  that fact.

- 1x7: JONAS-2 travels back to 2019, becoming JONAS-3.

- (1x7): YASIN-2, having been held for two days, is sent to 1953 in a
  time travel experiment, dying as YASIN-3.

*** November 10

- 1x8: JONAS-11 discusses time travel theory with TANNHAUS.  He has the
  BOOK with him.  Eventually he tells TANNHAUS that his theory is
  reality.  He shows him the MACHINE and asks to have it fixed.
  TANNHAUS asks him to leave.  TANNHAUS has an identical machine he
  has been working on.

*** November 11

- 1x9: HANNAH-1 suggests to KATHARINA-1 that REGINA fabricated the
  rape allegations.

- 1x9: EGON releases ULRICH-1 from jail.  He tells him that he feels
  ULRICH-1 is familiar.  (He is, of course.)

- 1x9: CLAUDIA-1 discovers GRETCHEN-2 in the cave of the power plant.
  From the dog’s perspective, she has been missing for one day.

- 1x9: KATHARINA-1, flanked by ULRICH-1 attack REGINA, believing that
  she is the source of the rape claims.  ALEKSANDER emerges and makes
  them leave, earning REGINA’s trust.

- 1x9: BERND tells CLAUDIA-1 about the power plant incident in the
  summer of 1986.  HELGE-Y knows about it, too.

- 1x9: HELGE-Y fails to show for EGON’s interview.  EGON looks for him
  at the cabin, but HELGE-Y successfully hides.  HELGE-Z, having
  traveled from 2019, watches.

- 1x9: At night, HELGE-Y and NOAH-Y are working in the BUNKER.
  HELGE-Y wants to stop experimenting, but NOAH-Y convinces him to
  continue the work.

*** November 12

- 1x10: HELGE-Z wakes up in the watchtower.

- 1x9: CLAUDIA-1 recruits ALEKSANDER to weld shut the door in the
  cave.

- 1x10: JONAS-13 returns to TANNHAUS, having traveled to 2019 to
  collect time travel fuel.  TANNHAUS shows him the MACHINE, as well
  as his own identical version, and that the PHONE (that he got from
  ULRICH-2 decades ago) can be used to control it.  He says that he
  would have been unable to complete the device unless he had seen the
  finished version that JONAS-13 brought.  TANNHAUS can not explain
  why he decided to help JONAS-13.  JONAS-13 takes his repaired
  machine with him, intending to close the passage.

- 1x10: HELGE-Z tries to explain to HELGE-Y that NOAH-Y is exploiting
  him for nefarious purposes.  HELGE-Y runs away.

- 1x10: HELGE-Y goes to NOAH-Y.  NOAH-Y tells him about a stranger who
  came to them when he was younger (JONAS-X).  JONAS-X then said that
  “nothing is in vain”, which later inspired NOAH-Y’s worldview.
  HELGE-Y remains loyal to NOAH-Y.  They plan to abduct JONAS-X next.

- 1x10: JONAS-4 arrives from 2019, intending to bring MIKKEL-2 back.
  He asks CHARLOTTE-2 about the date, and they talk about bringing
  people back from the dead.

- 1x10: INES offers to adopt MIKKEL-2.

- 1x10: JONAS-4 gets to MIKKEL-2’s bed, but NOAH-Y is there.  HELGE-Y
  attacks him from behind and subdues him.  He wakes up in the BUNKER.
  JONAS-Y talks to him from the other side of the door, but refuses to
  open it.  JONAS-13 explains that he is the elder JONAS, and that
  JONAS-4 must remain in the bunker for JONAS-Y to become who he is.

- 1x10: HELGE-Z causes a car accident with HELGE-Y.  HELGE-Z dies as
  an unidentified man in 1986.

- 1x10: JONAS-13 activates the MACHINE in the passage, closing it.
  Lights flicker everywhere.  At the same time he travels to 2019.  A
  wormhole appears in the BUNKER, allowing HELGE-1 in 1953 and JONAS-4
  in 1986 to see each other.  When they touch, HELGE-1 is transported
  to 1986, becoming HELGE-2, and JONAS-4 is transported to 2052,
  becoming JONAS-5.

** 1987

*** June 22

- 2x2: KATHARINA-1’s birthday is today.

- 2x2: While visiting CLAUDIA-Y, EGON sees GRETCHEN-2 and makes a
  remark about the similarity.  EGON wants to tell her he has cancer,
  but doesn’t.

- 2x2: CLAUDIA-Z visits CLAUDIA-1 in her office in the power plant.
  GRETCHEN-2 remembers the smell of both of them.

- 2x2: JONAS-Y and HANNAH-2 arrive from 2020 with the MACHINE.

- 2x2: NOAH-Y convinces MIKKEL-2 to stay away from the cave.  NOAH-Y
  was last seen in 2020 with BARTOSZ-1 and must be using the MACHINE
  at this point.

- 2x2: EGON visits HELGE-Y at the hospital.  HELGE-Y talks deliriously
  about the white devil, and that nobody can change events.

- 2x2: CLAUDIA-Z explains CLAUDIA-1 how to use the time machine, and
  gives her a map.  Then she travels away.

- 2x2: EGON visits ULRICH-2 in the mental hospital.  ULRICH-2 serves
  him the song lyrics about taking many lives.  EGON still doesn’t
  understand it.  ULRICH-2 says he knows when EGON will die.

- 2x2: JONAS-Y and HANNAH-2 watch INES and MIKKEL-2 from the garden
  window.  They probably go straight back to 2020, HANNAH-2 becoming
  HANNAH-3.

- 2x2: CLAUDIA-1, using the map from CLAUDIA-Z, unearths the MACHINE
  that CLAUDIA-Z had buried in the garden years before, in the 50s.

*** June 23

- 2x3: HELGE-2, having spent months in the 80s being impressioned by
  NOAH-Y, is returned to 1954 in the now functional time travel chair,
  becoming HELGE-3.  NOAH-Y then also travels to 1954 to miraculously
  make him speak, probably still using the MACHINE.

- 2x3: CLAUDIA-1, believing that she will soon lose REGINA,
  unsuccessfully tries to connect with her daughter.  After she
  leaves, CLAUDIA-1 remembers the book that HELGE-Y gave her.  She
  goes to him and he tells her about the struggle between good and
  evil, and that he was working for the side that attempts to make
  sure “none of it happens”.  He gives her NOAH’s name and asks her
  not to trust him.

- 2x3: EGON sits in his kitchen listening to the song about taking
  many lives.  He then goes to ULRICH-2 to ask him about it again, and
  ULRICH-2 says who he is, and that he is from the future.

- 2x3: CLAUDIA-1 goes to TANNHAUS.  He recognizes her from her eyes
  and tells her that ne never really wrote the BOOK.  TANNHAUS has
  been instructed to tell CLAUDIA-1 how to operate the device, which
  he learned from JONAS-Y in 1986.

- 2x3: EGON questions INES about MIKKEL-2’s parents.  INES is
  impatient.  She reluctantly gives him a photo of MIKKEL-2.

- 2x3: EGON goes to CLAUDIA-1’s office, to tell her he has cancer and
  that it is spreading.

- 2x3: EGON shows the picture of MIKKEL-2 to ULRICH-2.  ULRICH-2,
  shocked, demands to know where he is.  EGON is just as shocked, he
  clearly didn’t really believe this would cause a reaction.  ULRICH-2
  turns violent.

- 2x3: By the BARRELS, CLAUDIA-1 uses the MACHINE to travel to 2020,
  becoming CLAUDIA-2.

*** June 24

- 2x4: In the evening, CLAUDIA-3 returns from 2020, hoping to stop
  herself from disappearing and her father from dying on June 26.

*** June 25

- 2x5: CLAUDIA-3 reschedules a meeting from a French delegation, just
  like the article she read about her disappearance said that she
  would.  She goes to see EGON and urges him to move in with her, to
  try to avoid his death.

- 2x5: ULRICH-2 escapes from the mental hospital to find his son.  He
  uses the line about “not where, but when” to reveal himself to
  MIKKEL-2.

- 2x5: CLAUDIA-3 again pressures BERND on the incident, now one year
  ago.  He shows her the data that indicates the existence of the
  GOD-PARTICLE.  BERND wants it kept secret, at least until his death.

- 2x5: INES hears about ULRICH-2’s escape, and fears for MIKKEL-2.
  She comes home and cannot find him.  She calls EGON, telling him
  about ULRICH-2’s escape.  He immediately understands they are headed
  for the cave and calls the police.  ULRICH-2 and MIKKEL-2 are
  intercepted at the last moment.  ULRICH-2 threatens to kill EGON.
  This causes INES and MIKKEL-2 to go into hiding for a few months,
  supported by Child Protective Services.

- 2x5: FRANZISKA-2, ELISABETH-2, MARTHA-2, MAGNUS-2 and BARTOSZ-3
  arrive from 2019.  BARTOSZ-3 says he was told by NOAH-Y about
  JONAS-X and MARTHA-1 kissing, about REGINA’s cancer and JONAS’
  disappearance.  FRANZISKA-2 makes the connection between the name
  and ELISABETH’s earlier report of NOAH-Y.

- 2x5: As ULRICH-2 is being taken away, they drive past FRANZISKA-2,
  ELISABETH-2, MARTHA-2, MAGNUS-2 and BARTOSZ-3.  He recognizes them,
  but the police won’t stop.  They then return to 2020, becoming
  FRANZISKA-3, ELISABETH-3, MARTHA-3, MAGNUS-3 and BARTOSZ-4.

*** June 26

- 2x7: CLAUDIA-3 is recording memoirs about the GOD-PARTICLE in her
  office in the early morning, having lost track of time.

- 2x7: CLAUDIA-3 desperately tries to get EGON to move in with them
  before he dies.  She doesn’t want to let him out of her sight.
  During chemotherapy, EGON reveals his suspicions about time travel
  and eventually tells her about ULRICH-2, and that he is from the
  future.  EGON realizes CLAUDIA-3 believes her.

- 2x7: Back in EGON’s apartment, to collect his medication, CLAUDIA-3
  desperately tries to make him leave.  EGON begins to question her
  motivations, realizing she knows about time travel.  She denies
  everything, trying to keep him from the caves.  When EGON calls the
  station to search the caves, a fight breaks out, and CLAUDIA-3
  accidentally kills him.  In his dying breath, EGON realizes that
  CLAUDIA-3 is the white devil that HELGE-3 warned him about in 1954.
  CLAUDIA-3 does not call an ambulance.

- 2x7: At home, CLAUDIA-3 is interrupted by JONAS-8.  This is the
  version of JONAS that was swept away by CLAUDIA-Z on June 20, 2019.
  We may presume that he has spent at least a year of personal
  chronological time between then and now, being influenced by
  CLAUDIA-Z.  Before CLAUDIA-Z left him, she gave him a key to the
  house.  CLAUDIA-Z told him that it may not always happen this way
  (EGON dying).  “Next time” it may be different.  JONAS-8 takes her
  to the caves.

*** June 27

- 2x8: By the BARRELS, JONAS-8 tells CLAUDIA-3 that his future self
  tried to destroy the passage (on November 12), but failed and only
  closed it.  CLAUDIA-Z has indicated to JONAS-8 that it would be
  possible to change small details so that he is successful the next
  time.  JONAS-8 collects GOD-PARTICLE from the BARRELS.

- 2x8: JONAS-8 intends to reopen the passage.  He says he spent 12
  months (with CLAUDIA-Z) to realize that he has to help start the
  disaster that he wants to avert.  CLAUDIA-Z has told him everything
  about the past and the future.  He tells CLAUDIA-3 about the two
  sides.

- 2x8: JONAS-8 activates the MACHINE, reopening the passage.  JONAS-8
  and CLAUDIA-3 simultaneously travel to 2020, becoming JONAS-9 and
  CLAUDIA-4.  KATHARINA-2 arrives from 2020.

*** September 21

- 3x1: UNKNOWN arrives to assassinate BERND.  The motivation may have
  something to do with the master key to the power plant, which BERND
  has kept since his retirement.

*** September 22

- 3x2: KATHARINA-2 awakes in the Kahnwald house.  INES and MIKKEL-2
  are nowhere to be found.  There are missing posters for MIKKEL-2,
  which KATHARINA-2’s has been making.

- 3x2: MADS’ grave is placed in the graveyard and a service is held.
  JANA is dismissive, believing that an empty grave is pointless.  At
  the gathering, she publicly outs TRONTE as an adulterer, who was
  with CLAUDIA-1 when MADS went missing.

- 3x2: When searching for MIKKEL-2 in the school, ULRICH-1 tips
  KATHARINA-2 off to ULRICH-2’s existence (as “that lunatic”).  Later,
  the police tell her that INES and MIKKEL-2 are in hiding after the
  events of the summer.

- 3x2: TRONTE is still searching for CLAUDIA, whom he loves.  He tries
  to accept some fatherly responsibility for REGINA, who he believes
  may be his daughter (although she is not).  REGINA finds him creepy.

- 3x2: KATHARINA-2 goes to the mental hospital where her mother HELENE
  works.  She’s wearing the MEDALLION.  Upon telling her about the
  MEDALLION, HELENE agrees to let KATHARINA-2 see ULRICH-2.  They
  concoct a plan to break him out.

- 3x2: UNKNOWN kills JASMIN (the power plant secretary).  They are
  probably there to erase evidence of the GOD-PARTICLE, having entered
  with BERND’s master key.

- 3x2: Returning home, TRONTE reaffirms his commitment to JANA.

*** September 23

- 3x5: KATHARINA-2 plans ULRICH-2’s escape from the mental hospital.
  Later she attacks HELENE by the lake for her key card.  However,
  HELENE ends up killing her, dumping the body in the lake.  In the
  process, the MEDALLION ends up lost on the beach.  ULRICH-2 then
  fails to escape.

- 3x5: TANNHAUS says that, at the day of the accident involving his
  son and daughter, two strange women gave him baby CHARLOTTE-2.  The
  POCKETWATCH came with them.

- 3x5: PETER arrives in Winden, meeting CHARLOTTE-2 at the bus stop.

- 3x5: INES and MIKKEL-2 return to the Kahnwald house.  MIKKEL-2
  realizes that someone has been there.

** 1993

*** August 8

- (2x4): REGINA marries ALEKSANDER.

** 2019

*** ??

- ??: In the summer of 2019, the passage to 1986 and 1953 opens in the
  caves, because of an incident in the power plant’s volume control
  system in 1986.

*** June 20

- (2x4): The HOTEL opens for business.

- 2x6: MIKKEL-2 is reclusive.  Does he remember his own suicide?
  HANNAH-1 wants her husband to be more outgoing.  It seems like
  HANNAH-1 and ULRICH-1 are not yet having an affair.

- 2x6: JONAS-7 arrives from 1921, having jumped in time slightly off
  from the usual 33-year offset.

- 2x6: ALEKSANDER reads about the murder he committed in the fall
  of 1986.  It is still unsolved.

- 2x6: CHARLOTTE-2 and PETER are already having relationship problems.
  CHARLOTTE-2 does not want PETER at KATHARINA-1’s birthday party.

- 2x6: MARTHA-1, JONAS-1, MAGNUS-1 and BARTOSZ-1 are at the lake.
  BARTOSZ-1 tells a story about a woman who drowned there.  JONAS-1
  finds the MEDALLION buried in the sand.  He leaves early to teach
  INES how to use a tablet.  The MEDALLION stays behind.

- 2x6: JONAS-7 runs into KATHARINA-1, ULRICH-1 and MIKKEL-1.  MIKKEL-1
  offers him an “ultimate fist bump”.

- 2x6: After JONAS-1 leaves MARTHA-1, JONAS-7 shows up, behaving
  differently.  MARTHA-1 believes him to be JONAS-1.  He says they are
  perfect for each other, and tells her never to believe anything
  else.  They kiss.

- 2x6: MIKKEL-2 briefly sees MIKKEL-1 in the Kahnwald house, when he
  uses the bathroom.

- 2x6: JONAS-7 goes to MIKKEL-2 to prevent his suicide.  He uses the
  “ultimate fist bump” line to reveal himself.  MIKKEL-2 is confused
  because he had no intention of committing suicide.  JONAS-7 shows
  him the LETTER and says that MIKKEL-2’s suicide is the beginning of
  the loop.  (This is not true.)  MIKKEL-2 explains the exact events
  at his disappearance: that JONAS-7 led him away purposefully.
  MIKKEL-2 correctly realizes JONAS-7’s true purpose: to ensure that
  the suicide and disappearance both happen.  CLAUDIA-Z shows up,
  saying that JONAS-Z lied to JONAS-7.  JONAS-Z doesn’t want to fix
  anything, but to destroy things.  CLAUDIA-Z has seen the world
  without JONAS and it is not what he thinks it will be.  (When did
  she do this?)  CLAUDIA-Z leads JONAS-7 away to the cave. They will
  travel to some other time.  We next see JONAS-7 in on June 26, 1987,
  which we shall name JONAS-8.

- 2x6: At the party, MARTHA-1 gives JONAS-1 the MEDALLION, on a
  string.  MARTHA-1 is acting as if JONAS-1 remembers the conversation
  at the lake (which was actually JONAS-7).  They kiss, and eventually
  have sex, but MARTHA-1 must act very forward to make it happen.
  Later, HANNAH-1 makes advances on ULRICH-1.  They talk about a world
  without Winden, as they did on November 5, 1986.

- 2x6: PETER, unhappy, goes to see BERNADETTE.  FRANZISKA-1 spots him.

*** June 21

- 1x1: In the KAHNWALD house, MIKKEL-2 writes a suicide note based on
  what JONAS-7 showed him, instructing not to open before 22:13 on
  November 4.  Then he commits suicide by hanging.  The LETTER ends up
  in INES’ hands.

*** ??

- 1x1: Without MIKKEL-2, the relationship between INES and HANNAH-1
  deteriorates.  It seems HANNAH-1 has never particularly liked INES,
  or maybe new affair with ULRICH-1 has something to do with it.  INES
  stops seeing her grandson, and HANNAH-1 removes her from the family
  photo.

*** October 22

- 1x1: ERIK-1 goes missing, some time between 21:30 and 22:30.  He has
  been taken back to 1986 by HELGE-Y, becoming ERIK-2.

*** November 4

- 1x1: JONAS-1 awakes, the power is out again.  Wearing a yellow
  jacket, he meets PETER, his therapist.  He does not understand his
  dad’s suicide.

- 1x1: ULRICH-1 has breakfast together with his family: KATHARINA-1,
  MIKKEL-1, MARTHA-1 and MAGNUS-1.  MIKKEL-1 shows him a magic trick,
  saying that “the question isn’t how, the question is when”.

- 1x1: JONAS-1 is back in school for the first time in two months.
  BARTOSZ-1 has told everyone that he has been in France.

- 1x1: HELGE-Y exits the cave wearing a hooded jacket, having traveled
  from 1986.

- 1x1: JANA tells ULRICH-1 that she has seen a dark figure with a
  large head in the forest (HELGE-Y).  ULRICH-1 doesn’t believe her.
  She also found a wrapper for a RAIDER chocolate bar.

- 1x1: JONAS-1, MARTHA-1, MIKKEL-1, MAGNUS-1 and BARTOSZ-1 gather in
  the forest.  JONAS-1 tells MARTHA-1 about a glitch in the matrix,
  and MIKKEL-1 offers JONAS-1 an “ultimate fist bump”.

- 1x10: PETER goes to sit in the BUNKER.  A wormhole opens and MADS-2
  drops to the floor, dead.  He has his ID card around the neck.
  PETER calls TRONTE.  After he arrives, CLAUDIA-Z shows up.  TRONTE
  recognizes her.  Together, they take MADS-2 to a place in the
  forest.  Before she leaves, she gives them the NOTEBOOK, with the
  last few pages missing.

- 1x1: HELGE-Z interrupts a parent’s meeting in the school, declaring
  that “it’s going to happen again”.

- 1x1: INES honors the instructions on the LETTER from MIKKEL-2, opens
  it and reads it.

- 1x1: The kids find ERIK’s bag of things, including his phone, which
  BARTOSZ-1 takes in his posession.

- 1x1: HELGE-Y travels back to 1986.  This causes the lights to
  flicker in the forest, the kids run away and MIKKEL-1 goes missing.
  JONAS-7 has taken him back to 1986, becoming MIKKEL-2, where he
  spends the night before exiting the cave.

- 1x1: HELGE-Z says to CHARLOTTE-2 that it is too late.

*** November 5

- 1x1: PETER calls CHARLOTTE-2 but is unable to articulate what he
  wants to say.

- 1x1: A child’s body is found in the forest, surrounded by 80’s
  effects and a peculiar red soil.  Around his neck a PENNY
  from 1986. It’s MADS-2.

- 1x2: JONAS-10 arrives from 2052.

- 1x2: PETER is crying in his car, next to the BUNKER.

- 1x2: TRONTE is washing blood off his clothes.  JANA confronts him,
  she knows that he was out of the house last night.  TRONTE avoids
  her questions.  She does not believe him, for good reason: TRONTE
  has had affairs before.

- 1x2: ALEKSANDER, anticipating a police search, orders JÜRGEN to get
  rid of the BARRELS in secret.  Later that day they are loaded onto a
  truck.

- 1x2: JONAS-10 checks in to the HOTEL.  He has a large amount of time
  travel material with him, including the BOOK and the MACHINE, which
  is broken.

- 1x2: HELGE-Y arrives from 1986.  At some point the same day he also
  travels back.

- 1x2: In his father’s studio, JONAS-1 discovers a detailed map of the
  cave.

- 1x2: ULRICH-1 searches the OBENDORF property, finding a jar of coins
  and a bag of drugs.  ERIK was dealing.

- 1x2: TRONTE leaves during the night again.  JANA notices.  The
  lights flicker all over town.

- 1x3: ULRICH-1 searches the caves.  He can hear MIKKEL-2 from 1986.

*** November 6

- 1x4: HELGE-Z repeats that “it” must stop.  He’s talking about his
  younger self and NOAH-Y.

- 1x4: JONAS-1 goes exploring in the cave, armed with the map from his
  father.  He is unable to find the way.  JONAS-10 is watching.  When
  he returns, a red string is tied around his bike handle.

- 1x4: CHARLOTTE-2 discovers from the wildlife camera that PETER was
  out driving around the time of MIKKEL-1’s disapperance.  PETER
  cleans red soil out of his car.  On the phone, he again avoids
  revealing what he knows.  BERNADETTE tells CHARLOTTE-2 that he was
  not with her.

- 1x4: CHARLOTTE-2 finds the red soil around the CABIN.  While
  investigating the BUNKER, she is interrupted by a call about
  ULRICH-1 having been caught entering the power plant.  She asks
  PETER to pick up ELISABETH.  PETER again fails to communicate to
  CHARLOTTE-2 what he knows.

- 1x4: HELGE-Z leaves the home.  He is later picked up by the police,
  chanting about having to “tell him”, and that “it must stop”.

- 1x4: On the way home from school, ELISABETH-1 finds a RAIDER
  wrapper, presumably dropped by HELGE-Z who is currently kidnapping
  YASIN-1.  She meets NOAH-Y, who gives her the POCKETWATCH with
  instructions to pass it on to CHARLOTTE-2.  At some point she drops
  her hat.

- 1x4: CHARLOTTE-2 finds ELISABETH’s hat.  Later, ELISABETH-1 comes
  home and gives CHARLOTTE-2 the POCKETWATCH, also telling her about
  NOAH-Y.  CHARLOTTE-2 recognizes it.

- 1x4: JONAS-10 sneaks into JONAS-1’s bedroom and writes a hint on the
  map: “follow the signal”.

*** November 7

- 1x4: YASIN-1 is kidnapped by HELGE-Y, who says that NOAH-Y sent
  him.  They take him back to 1986 for time travel experiments, where
  he becomes YASIN-2.

- 1x5: CHARLOTTE-2 confronts PETER about the photo from the wildlife
  camera.  PETER calls her crazy.

- 1x5: NOAH-Y calls BARTOSZ-1 on ERIK’s phone.  They plan to meet
  later.  BARTOSZ-1 wants JONAS-1 to accompany him, believing NOAH-Y
  to be a drug dealer.

- 1x5: JONAS-10 leaves the HOTEL, intending to come back in a few days
  (although he will not).  He leaves behind many of his time travel
  effects on the walls of the room, but takes with him the broken
  MACHINE.  He also gives REGINA a package intended for JONAS-1, with
  objects that will help him find the passage in the cave.

- 1x5: ULRICH-1 ends his affair with HANNAH-1.  She does not take it
  well.

- 1x5: JONAS-1 meets JONAS-10 at the graveyard.  JONAS-10 says that
  they don’t know each other, but that JONAS-1’s father saved his life
  a long time ago.  (By committing suicide.)  JONAS-10 offers more
  cryptic advice, which will not be the first time.  Later, JONAS-10
  goes through the passage to 1986, becoming JONAS-11.

- 1x5: JONAS-1 goes to see MARTHA-1’s theater practice, and fails to
  join BARTOSZ-1 when meeting NOAH-Y.  JONAS-1 tell her that he was
  not in France, and they kiss.

- 1x5: BARTOSZ-1 meets NOAH-Y, who has the NOTEBOOK.  He explains some
  of the things that are about to happen, in order to gain BARTOSZ-1’s
  trust.

- 1x5: KATHARINA-1 confronts ULRICH-1 about his affair.  He denies it.

- 1x5: JONAS-1 receives the package from JONAS-10.  It contains a LAMP,
  a GEIGER COUNTER, and the LETTER written by MIKKEL-2

*** November 8

- 1x6: ULRICH-1 listens to a recording of JANA giving testimony after
  MADS-1 disappeared.  She said that TRONTE was at home that night,
  but ULRICH-1 can remember that he wasn’t.

- 1x6: REGINA receives word that she has breast cancer.

- 1x6: JONAS-1 discovers the hint from JONAS-10 on the map.

- 1x6: ULRICH-1 confronts TRONTE about the night MADS disappeared, and
  TRONTE rejects that he has anything to do with MIKKEL-1’s
  disappearance.  JANA again covers for him, saying he was at home
  (although she knows that he was not).  After TRONTE leaves, ULRICH-1
  asks JANA about her testimony in the 80s.  JANA explains that TRONTE
  was sleeping with CLAUDIA at the time, which is probably true.  She
  says that REGINA was the last to see MADS alive.

- 1x6: JONAS-1, armed with knowledge and equipment, re-enters the
  cave.

- 1x6: KATHARINA-1 finds proof that ULRICH-1 and HANNAH-1 have an
  affair.

- 1x6: ULRICH-1 asks REGINA about the night that MADS went missing.
  REGINA is unhelpful because she hates ULRICH-1.  She explains that
  MADS was following her home, being afraid after what ULRICH-1 and
  KATHARINA-1 did to her that summer (tied her up to a tree),
  indirectly blaming ULRICH-1 for his brother’s disappearance.
  ULRICH-1 is likewise antagonistic because he believes REGINA
  fabricated the rape allegations in 1986.  REGINA denies it and
  ULRICH-1 correctly realizes that it was HANNAH-1.  The police
  archives confirm it.

- 1x6: ALEKSANDER learns about REGINA’s cancer test results, calling
  her to comfort her.

- 1x6: ULRICH-1 angrily confronts HANNAH-1 about the rape allegations.

- 1x6: PETER and TRONTE wait in the BUNKER for the exact moment when
  JONAS-1, having found the passage, travels to 1986 (becoming
  JONAS-2).  MARTHA-1 breaks down on stage and is brought out by
  KATHARINA-1.  In the school hallways, KATHARINA-1 and REGINA have a
  fight, which is broken up by MAGNUS-1.

- 1x6: ULRICH-1 finally realizes that the dead child found on November
  5 is MADS-2.

*** November 9

- 1x7: ULRICH-1 realizes that HELGE-Y never gave testimony in the case
  of the disappearance of MADS-1.

- 1x7: While searching the power plant grounds, CHARLOTTE-2 discovers
  recent tire tracks near the cave where the BARRELS were stored.  She
  also finds remains of yellow paint there.

- 1x7: ULRICH-1, now suspecting HELGE-Z, visits him in the care home.
  HELGE-Z, recognizing him as his attacker in 1953, panics, but also
  hints to ULRICH-1 that he can change the past.

- 1x7: Based on his recent behaviour, CHARLOTTE-2 suspends ULRICH-1.
  When he comes home, KATHARINA-1 tells him that she knows about him
  and HANNAH-1.

- 1x7: JANA tells ULRICH-1 that in 1986 she saw NOAH-Y argue with a
  man (HELGE-Y), and today she saw HELGE-Y again.

- 1x7: CHARLOTTE-2 calls PETER and asks him about the cabin.  PETER
  mostly avoids her questions.  HELGE-Y had an accident on November
  12, 1986.

- 1x7: JONAS-3 arrives from 1986, having been gone the whole day.  In
  the BUNKER, CHARLOTTE-2 finds a piece of blue wallpaper.  When
  JONAS-3 comes home, he burns the LETTER.

- 1x7: ULRICH-1 goes to see HELGE-Z again, but he is not there.  He
  finds the BOOK by the bedside, with a PENNY on a red string used as
  bookmark.  He brings these things with him, when he follows HELGE-Z
  through the forest.  He makes a call to CHARLOTTE-2’s voice mail,
  which is the last sign of life of ULRICH-1.

- 1x7, 1x8: ULRICH-1 follows HELGE-Z to the passage.  While HELGE-Z
  travels to 1986, ULRICH-1 travels to 1953, becoming ULRICH-2.

*** November 11

- 1x9: KATHARINA-1 reveals to CHARLOTTE-2 that ULRICH-1 is missing.
  KATHARINA-1 then goes to HANNAH-1, who lies to her about who
  really loved whom.  KATHARINA-1’s mental state is falling apart.

- 1x9: CLAUDIA-Z visits BARTOSZ-1, and gives him a photo of her and
  REGINA from the 80s.

- 1x9: HANNAH-1 blackmails ALEKSANDER to do his utmost to destroy
  ULRICH-1.  ALEKSANDER has an insider in the police: TORBEN.  In a
  few days they will bring the BARRELS back to the cave.

- 1x9: JONAS-3, knowing that MARTHA-1 is his aunt, tells her that it
  would be wrong for them to be together.  They kiss.  MARTHA-1 is
  presumably confused because JONAS-7 told her on June 20 that they
  are perfect for each other, and for her never to believe anything
  else.

- 1x9: REGINA, cleaning JONAS-10’s hotel room, finds all his time
  travel effects.

- 1x9: At night, BARTOSZ-1 tells NOAH-Y that everything he predicted
  actually happened.  NOAH-Y recruits BARTOSZ-1 as his aide.

- 1x9: JONAS-12 collects time travel fuel from the BARRELS in the
  truck.

*** November 12

- 1x10: HELGE-Z is reported missing.

- 1x10: JONAS-3 visits INES and finds out that she knew that MIKKEL-2
  came from the future.  She gives him the LETTER.  JONAS will carry
  it with him and eventually give it to his younger self on November
  7, 2019.

- 1x10: PETER and TRONTE are talking in the BUNKER.  Everything that
  CLAUDIA-Z told them would happen (in the NOTEBOOK) has happened.
  But after today, the pages are torn out.

- 1x10: JONAS-3 travels through the passage to 1986, becoming JONAS-4.

- 1x10: CHARLOTTE-2 finds a picture of ULRICH-2 in the newspaper
  from 1953.  PETER asks her to join him in the cabin to talk.

- 1x10: NOAH-Y tells BARTOSZ-1 that JONAS-13 intends to close the
  passage, but CLAUDIA-Z has lied to him.  He also explains that there
  two groups fighting to control time travel (Sic Mundus and Erit Lux)
  and that he belongs to the “light” as opposed to the “dark”, and
  that CLAUDIA-Z belongs to the latter.  He shows BARTOSZ-1 the
  NOTEBOOK.  Later, NOAH-Y probably travels to 1920.

- 1x10: JONAS-13 activates the MACHINE in the passage, closing it.
  Lights flicker everywhere.  At the same time, JONAS-13 travels
  to 2019 as JONAS-14.

** 2020

*** June 21

- 2x1: REGINA has lost most of her hair.

- 2x1: CLAUSEN arrives to investigate the disappearances.  There are
  six vanished people in 2019.

- 2x1: KATHARINA-1, based on ULRICH-1’s notes, is investigating the
  cave.

- 2x1: ALEKSANDER is preparing for the decommissioning of the power
  plant on June 28.  The BARRELS will be stored in a concrete pit.

- 2x1: JONAS-14 reveals himself to HANNAH-1.  He tried to destroy the
  passage, but succeeded only in closing it.  Now he is intending to
  “put an end to everything, once and for all”.

- 2x1: MARTHA-1 and MAGNUS-1 finds ULRICH-1’s old notes, realizing
  that KATHARINA-1 is looking through the caves for the door.

- 2x1: In TANNHAUS’ shop, ELISABETH-1 and PETER discover and old
  photograph of NOAH-Y.  They take it to the BUNKER, where they have
  been collecting evidence for their own investigation together with
  CHARLOTTE-2, and show it to her.

- 2x1: NOAH-Y arrives from 1921, probaby with the MACHINE, and is
  greeted by BARTOSZ-1.  They go back into the cave, probably to
  travel.  Over the next few days we will not see BARTOSZ, but he has
  certainly been time traveling, so we will now name him BARTOSZ-2.

- 2x1: TORBEN collects the BARREL truck from BERNADETTE.  They are
  brought to the pit in the power plant and encased in concrete.

*** June 22

- 2x2: CHARLOTTE-2 is curious why CLAUSEN wants to start the
  interviews with REGINA.  He has hidden motives: he already now
  suspects ALEKSANDER having murdered his brother in 1986.  CLAUSEN
  sees the photo of Sic Mundus, realizing CHARLOTTE-2 is hiding things
  from him.

- 2x2: JONAS-14 shows HANNAH-1 the MACHINE.  He wants to show her
  MIKKEL-2’s secret.

- 2x2: REGINA shows CLAUSEN and CHARLOTTE-2 the time travel effects
  found in JONAS-Y’s room and she also tells them about the package
  she delivered to JONAS-X.

- 2x2: JONAS-14 and HANNAH-1 travel to 1987 using the MACHINE.
  HANNAH-1 becomes HANNAH-2.  They probably come straight back,
  HANNAH-2 becoming HANNAH-3 and JONAS-14 now JONAS-16.

*** June 23

- 2x3: CLAUDIA-2 arrives from 1987 with the MACHINE.  She sees REGINA
  dying from cancer on the balcony.

*** June 24

- 2x4: CHARLOTTE-2 finds the BLUEPRINTS in TANNHAUS’ old shop.
  HANNAH-3 calls her.

- 2x4: FRANZISKA-1, ELISABETH-1, MARTHA-1 and MAGNUS-1 team up, and
  want to enter the caves to look for the door.

- 2x4: CLAUSEN pressures ALEKSANDER about his last name.  ALEKSANDER
  claims that his birth name was Köhler.  They are going to see
  HANNAH-3 next.  (HANNAH-3 will miss her appointment.)

- 2x4: CHARLOTTE-2 comes to HANNAH-3 and JONAS-16.  They bring her up
  to speed.  She realizes he was the man in the HOTEL.  JONAS-16
  identifies NOAH-Y in the photo from 1921 as “one of them” (Sic
  Mundus - The Travelers).

- 2x4: CLAUDIA-2 goes to the library to look up information from the
  time of 1987 to now.  She discovers that she was last seen in the
  80s on June 26 - two days from now, and that EGON also died on that
  day.

- 2x4: CHARLOTTE-2 takes HANNAH-3 and JONAS-16 to the BUNKER, where
  she and PETER have been collecting time travel evidence and
  information.  HANNAH-3 learns the location of ULRICH-2.  PETER says
  that CLAUDIA-Z had instructed him and TRONTE on what to do, and knew
  exactly what would happen when.  PETER still has the NOTEBOOK, with
  the last pages still ripped out.  HANNAH-3 insists that they should
  tell KATHARINA-1.  They do, but she acts hostile and refuses to join
  the group, believing it to be a hoax.

- 2x4: FRANZISKA-1, ELISABETH-1, MARTHA-1 and MAGNUS-1 find BARTOSZ-2
  in the caves.  He’s carrying the MACHINE, probably having just
  returned after traveling with NOAH-Y incrementally back to 1921 over
  the last three days.  They tie him up and leave him, taking the
  MACHINE.

- 2x4: KATHARINA-1 goes to the school to find MIKKEL-2’s old classs
  photo from the 80s and breaks down.

- 2x4: In the BUNKER, JONAS-16 says that everything will happen the way
  it always have, but that JONAS-Z said there is a loophole.
  (Although he hides the fact that JONAS-Z is ADAM).  He intends to
  stop JONAS-Z’s plans to start the last cycle.  CLAUDIA-Z tried to do
  it, but she became exactly what she was trying to fight.  (In
  reality, she has found the solution.  It is JONAS-16 who is
  perpetuating the cycle.)

- 2x4: CLAUDIA-2 returns to 1987, becoming CLAUDIA-3.

*** June 25

- 2x5: KATHARINA-1 tries to reconciliate with her children, but
  MARTHA-1 reject her.

- 2x5: REGINA and ALEKSANDER notice that BARTOSZ hasn’t been at home
  tonight.  Has he been at home at all since June 21?

- 2x5: HANNAH-3 tells KATHARINA-1 about the MACHINE.  KATHARINA-1
  wants to know how it works, but JONAS-16 has brought it with him.
  (Where is he?)  CLAUSEN shows up and asks about the drawing of
  JONAS-Y.  Both of them lie and say they haven’t seen him.  After
  KATHARINA-1 leaves, CLAUSEN pressures HANNAH-3 on her payments from
  ALEKSANDER.

- 2x5: JONAS-16 goes to MARTHA-1’s room and puts the MEDALLION on her
  bed.

- 2x5: FRANZISKA-1, ELISABETH-1, MARTHA-1 and MAGNUS-1 return to the
  cave with the MACHINE.  NOAH-Y is watching (how did he get here?).
  BARTOSZ-2 operates the machine for them and they travel to 1987,
  becoming FRANZISKA-2, ELISABETH-2, MARTHA-2 and MAGNUS-2, BARTOSZ-3.

- 2x5: JONAS-16 tells CHARLOTTE-2 that he doesn’t know who her parents
  are.  He thinks CLAUDIA-Z has been using himself, TANNHAUS, PETER
  and others.  He shows her the MACHINE that CLAUDIA-Z asked TANNHAUS
  to build.

- 2x5: CHARLOTTE-2 then goes back to TANNHAUS’ shop to find the
  BLUEPRINTS.  NOAH-Y enters, now presumably aware of the identity of
  his daughter.  CHARLOTTE-2 believes him (correctly) to be a
  murderer.  NOAH-Y laments that he cannot change her mind about him,
  but maybe one day she will understand.  NOAH-Y has the NOTEBOOK
  (with the missing pages).  He tells her that he’s her father.
  NOAH-Y is of the opinion that JONAS-Z always knew that CHARLOTTE-2
  was his daughter.  Having read the last pages, he warns her of the
  apocalypse, that only the people in the bunker will survive, and
  says that he intends to kill JONAS-Z.

- 2x5: FRANZISKA-3, ELISABETH-3, MARTHA-3, MAGNUS-3 and BARTOSZ-4
  arrive from 1987.  MARTHA-3 finds the MEDALLION on her bed that
  JONAS-Y put there.

*** June 26

- 2x7: JONAS-16 awakes.  HANNAH-3 is missing, having taken the
  MACHINE.  She has taken it to travel to 1954, becoming HANNAH-4.

- 2x7: FRANZISKA-3, ELISABETH-3, MARTHA-3, MAGNUS-3 and BARTOSZ-4
  debate what to do.  MARTHA-3 has the MEDALLION.  They resolve to
  confide in the adults.

- 2x7: CLAUSEN confront ALEKSANDER with the evidence suggesting that
  he is his brother’s killer, and arrests him.

- 2x7: MARTHA-3 goes to find HANNAH-3, but she is not there.  JONAS-16
  reveals his identity to her by talking about a glitch in the matrix.
  He asks whether she found the MEDALLION.

- 2x7: Next, KATHARINA-1 comes to the Kahnwald house and breaks in
  with an axe.  She distrusts JONAS-16, and her mental state is
  deteriorating.  KATHARINA-1 explains the deal with MIKKEL to
  MARTHA-3, that she is related to JONAS.  KATHARINA-1 wants the
  MACHINE, but it is gone.  MARTHA-3 says that they have a fully
  functional MACHINE already.  KATHARINA-1 takes MARTHA-3 away.

- 2x7: FRANZISKA-3, ELISABETH-3 and MAGNUS-3 have told CHARLOTTE-2 and
  PETER about their recent time travel and realize that they already
  know.  MARTHA-3 calls MAGNUS-3 and tells him about JONAS-16.
  CHARLOTTE-2 recommends them to stay out of things.  FRANZISKA-3
  explodes in anger.

- 2x7: MAGNUS-3 brings the MACHINE to MARTHA-3 and KATHARINA-1.
  KATHARINA-1 takes it, but does not immediately use it.  MARTHA-3
  tells MAGNUS-3 that MIKKEL-2 and ULRICH-2 are still alive, just in
  another time.

*** June 27

- 2x8: JONAS-16 pleads for MARTHA-3 to come with him before the
  apocalypse happens.  MARTHA-3 says that they aren’t right together,
  and asks him to leave.  He has seen her die before (at the
  apocalypse, as his younger self), and will not do it again.  He
  forces her to the BUNKER, which is the only safe place, and locks
  her in there.  JONAS-16 is losing hope that he can still change
  things, but feels he must try.

- 2x8: At the bridge, BARTOSZ-4 finds out from MAGNUS-3 and
  FRANZISKA-3 that KATHARINA-1 has the MACHINE.  BARTOSZ-4 thinks that
  is not right, and laments that NOAH-Y didn’t tell him what to do.
  They go to find the MACHINE.

- 2x8: KATHARINA-1 has taken the MACHINE to the Kahnwald house, trying
  to find JONAS-16 (presumably, to figure out to operate it).  He’s
  not there, but she finds the cave exploration gear instead.  When
  JONAS-16 returns, he tells her the futility of changing the past
  (although, that’s what he’s trying to do).  He may not be able to
  prevent himself from becoming JONAS-Z, but he may still try to stop
  him now.

- 2x8: TORBEN tells CHARLOTTE-2 about the BARRELS, which are now
  buried in concrete in the power plant.  CHARLOTTE-2 realizes that
  CLAUSEN is about to trigger the apocalypse.

- 2x8: PETER intends to ELISABETH-3 to the BUNKER in order to survive.

- 2x8: In 1987, JONAS-8 reopens the passage, causing a light effect in
  the BUNKER that MARTHA-3 sees, flickering lights and dead birds.
  JONAS-16 tells KATHARINA-1 that the passage is open.  KATHARINA-1
  takes the cave exploration gear, intending to use the passage to
  find MIKKEL-2.  She leaves the MACHINE with JONAS-16, and later goes
  through the passage to 1987, becoming KATHARINA-2.

- 2x8: When PETER and ELISABETH-3 arrive at the BUNKER, MARTHA-3 is
  able to escape.

- 2x8: MAGNUS-3, FRANZISKA-3 and BARTOSZ-4 arrive at the Nielsen’s
  home, but the MACHINE is not there.  FRANZISKA-3 gets the message
  that PETER and ELISABETH-3 are in the BUNKER.  They will wait for
  MARTHA-3 and KATHARINA-1 for half an hour before going to the
  BUNKER.

- 2x8: JONAS-9 and CLAUDIA-4 arrive from 1987.  They have a MACHINE.
  JONAS-9 instructs CLAUDIA-4 to get REGINA and take it to the BUNKER,
  so that they may escape the apocalypse.  JONAS-9 wants to find his
  mother, and MARTHA-3.

- 2x8: At the Kahnwald house, NOAH-2 walks in on JONAS-16, having
  traveled from 1921.  He expects them to be friends, and for JONAS-16
  to eventually become JONAS-Z.  He has a NOTE from MARTHA.  (Is this
  a fabrication?  We haven’t seen MARTHA write anything like this.)
  NOAH-2 tasks him to save MARTHA, FRANZISKA-3, MAGNUS-3, and later
  (when?) himself and AGNES.  JONAS-Y takes the MACHINE and goes to
  the Nielsen’s, saving FRANZISKA-3, MAGNUS-3 and BARTOSZ-4 by
  bringing them to 1888, becoming JONAS-17, FRANZISKA-4, MAGNUS-4 and
  BARTOSZ-5.  NOAH-2 then goes to the bunker, saving himself and
  meeting the future mother of his child, ELISABETH-3.

- 2x8: Upon entering the BUNKER, PETER recognizes CLAUDIA-4.

- 2x8: During an inspection, CLAUSEN insists to break open the
  concrete layer covering the BARRELS.  CHARLOTTE-2 goes there
  intending to stop them, but fails, and they open the BARRELS.  In
  the wormhole mass, CHARLOTTE-2 sees ELISABETH-Y in 2053 and travels
  there, becoming CHARLOTTE-3.

- 2x8: JONAS-9 arrive at the Kahnwald house at the same time as
  MARTHA-3.  They kiss, but are interrupted by JONAS-Z, who has just
  traveled from 1921.  JONAS-Z shoots and kills MARTHA-3.  He then
  circles the date on the calendar.  The apocalypse allows a splitting
  of the timelines.  One version of JONAS-8 is rescued by MARTHA-Xb
  (she has a scar under her left eye in A-world and under her right
  eye in B-world) and taken to B-world on November 4, 2019, becoming
  JONAS-9b.  In the other version, MARTHA-Xb2 is stopped by BARTOSZ-Xb
  before entering.  He tells her that in reality JONAS-Z does not
  intend to stop the apocalypse.  In this case, JONAS-8 hides in the
  basement of the Kahnwald house, surviving the apocalypse and
  becoming JONAS-9.  BARTOSZ-Xb and MARTHA-Xb2 travel away using the
  ORB.  We next see them in B-word, in the burned-down Erit Lux
  headquarters.  In the third case, JONAS-Z arrives from 2053 under
  instructions by CLAUDIA-Zb, and takes JONAS-8 away with the ORB to
  become JONAS-9c.  They travel to world B at the time of the
  apocalypse, November 8, 2019.

- 2x8: The apocalypse happens. This date is marked as “beginning of
  the last cycle” in the NOTEBOOK.

*** September 22

- 3x2: CLAUDIA-4 has established herself in the police station after
  the apocalypse.  REGINA is there too, slowly dying of cancer.  In
  the BUNKER, CLAUDIA-4 has begun establishing her wall of photos.

- 3x2: ELISABETH-3 and PETER are living out of a caravan, perhaps
  BERNADETTE’s.  When leaving they are followed by NOAH-2.  They pass
  a military road block to search for CHARLOTTE and FRANZISKA, who are
  not there to be found.

- 3x2: CLAUDIA-4 records tapes with whatever she knows.  She is out of
  GOD-PARTICLE fuel.  She believes she may be able to save everyone by
  returning to the past if she can stabilize the GOD-PARTICLE mass.

- 3x2: In the Kahnwald house, while PETER is upstairs, NOAH-2 shows
  up.  They communicate by writing.  He says he sleeps in the cave.
  When PETER arrive he accuses him of following them.  He knows PETER
  is about to die, and says he will protect ELISABETH-3 after that
  happens.

- 3x2: TRONTE, having somehow survived the apocalypse.  He kills
  REGINA, because “it must happen”, because someone (CLAUDIA-Z) told
  him it’s the only way to save her, so that CLAUDIA-4 will be motived
  to change it.  CLAUDIA-4 later returns to find her lifeless body.

- 3x2: ELISABETH-3 confronts PETER about the NOTEBOOK, which he still
  has, asking why he carries it everywhere.

- 3x2: NOAH-2 is hard at work clearing out the tunnel in the caves.

*** September 23

- 3x5: CLAUDIA-4 is visited by CLAUDIA-Yb in the ruins of the police
  station.  She is there to recruit her efforts for Erit Lux.
  CLAUDIA-4 is of the belief that JONAS is dead.  She is told that she
  must make efforts to ensure that the cycle perpetuates.  For this
  purpose, she is given the NOTEBOOK, freshly authored by the hands of
  UNKNOWN.  She must lead JONAS, NOAH and ELISABETH, and then later
  turn against them.  CLAUDIA-Yb travel away.

- 3x5: While on their way through the road block, ELISABETH-3, holding
  the POCKETWATCH, refuses to follow PETER, accepting now the death of
  her mother and sister.

- 3x5: A man attacks ELISABETH-3 and PETER in their caravan,
  eventually causing PETER’s death.  ELISABETH-3 goes to NOAH-2 for
  protection.

*** September 24

- 3x6: CLAUDIA-4 approaches the GOD-PARTICLE mass in the power plant.
  He is stopped by JONAS-9.  Where he has been the last three months
  is unclear.  He explains the significance of the mass, and that he
  needs to make it work.  He asks how she knew he was here.
  Presumably, she got it from the NOTEBOOK, but she says she was
  looking for fuel for the MACHINE.  Unfortunately, the MACHINE was
  broken in the apocalypse.

** 2021

*** ??

- 3x7: NOAH-2 and ELISABETH-3 are working to clear the passage in the
  cave.  ELISABETH-3 has the POCKETWATCH.  NOAH-2 tells her about
  paradise.  They are waiting for the passage to open, as JONAS-Z has
  promised.

** 2023

*** ??

- 3x7: CLAUDIA-4 and JONAS-9 are working with the GOD-PARTICLE mass,
  but some sort of shield is preventing access to it.  JONAS-9 is
  getting despondent and CLAUDIA-4 is trying, unsuccessfully, to
  encourage him.  JONAS-9 leaves and returns to the Kahnwald house,
  where he saw MARTHA-3 die.  He goes to the attic and attempts
  suicide, but NOAH-2 interferes and saves him.  He gives JONAS-9 a
  gun, which fails to fire when pointed toward JONAS-9’s head but
  works fine when pointed elsewhere.

- 3x7: NOAH-2 shows JONAS-9 the passage.  It is sealed.  They’re just
  waiting for it to open and for JONAS-Z to lead them to paradise.
  JONAS-Z has said that NOAH-2 and JONAS-9 will become friends before
  JONAS-9 betrays NOAH-2.

** 2040

- 3x7: NOAH-2, JONAS-9 and CLAUDIA-4 continue work with the
  GOD-PARTICLE mass.  They succeed in penetrating the shield around
  it, however something still isn’t working.  NOAH-2 later indicates
  to JONAS-9 that maybe CLAUDIA-4 is sabotaging the work.  JONAS-9 in
  turn questions NOAH-2’s fanatical devotion to JONAS-Z and his belief
  in paradise, believing he can still change events.  He seems to
  believe this because of things CLAUDIA-4 has said.  ELISABETH-3
  appears to be pregnant.

- 3x7: CLAUDIA-4 is visited by CLAUDIA-Zb.  It is made clear that
  CLAUDIA-4 really is sabotaging the work, and that the GOD-PARTICLE
  mass must continue to fail until a point in the future.  CLAUDIA-4
  questions why she is working to perpetuate the cycle when her older
  self told her that it’s possible to ensure REGINA can live.  She
  points a gun to CLAUDIA-Zb and kills her, resolving to find a way to
  dissolve the knot, independently of JONAS-Z and MARTHA-Zb.  From the
  dead CLAUDIA-Zb, CLAUDIA-4 obtains an ORB.  She uses it to travel to
  world B, disguised as CLAUDIA-Zb, becoming CLAUDIA-5.

** 2041

- 3x7: While lecturing ELISABETH-3 on paradise, she and NOAH-2 are
  overheard by ELISABETH-Y and CHARLOTTE-5, who have traveled
  from 2053.  They sneak into the cabin and takes young CHARLOTTE-1.
  ELISABETH-Y is in tears, seeing her daughter again who was taken
  from her years before (in her personal timeline).  CHARLOTTE-5 also
  grabs the POCKETWATCH.

- 3x7: In the BUNKER, NOAH-2 confronts JONAS-9, who he believes took
  his daughter, possibly aided by CLAUDIA.  JONAS-Z had warned him
  that JONAS-9 would eventually betray him.  NOAH-2 later takes the
  NOTEBOOK (with the last pages missing) and sets out on a mission to
  recover CHARLOTTE.  We next see him as NOAH-3 in 1920.

** 2052

*** ??

- 3x7: Having finally stabilized the GOD-PARTICLE mass, CLAUDIA-6
  instructs JONAS-9.  She gives him the MACHINE and says that TANNHAUS
  will repair it.  She also gives him the BOOK.  She says he must
  destroy the passage and the knot, that this time it will succeed and
  that he must never lose hope.  After he leaves to travel to 2019,
  becoming JONAS-10, she rips out the last few pages of the NOTEBOOK.
  Afterward, she travels to 1986 to find CLAUDIA-1, becoming CLAUDIA-7.

*** November 12

- 1x10: JONAS-5 arrives from 1986 through the wormhole in the bunker.
  He is arrested by SILJA-X and her paramilitary group, led by
  ELISABETH-Y.

** 2053

*** ??

- 2x1: JONAS-5 has taken to live in the old Kahnwald house.  On the
  calendar, the day of June 27, 2020 is marked with a circle.  In the
  BUNKER, he listens to the recorded memoirs of CLAUDIA-Y, explaining
  what she knows about the apocalypse.  He finds the MEDALLION there.

- 2x1: ELISABETH-Y and SILJA-X are lecturing JONAS-5 about
  “paradise”.  They are trying to prevent him from passing the wall
  into the power plant ruins.  JONAS-5 sneaks in anyway and finds the
  GOD-PARTICLE mass in there.

- 2x2: Based on CLAUDIA’s recordings, JONAS-5 succeeds in stabilizing
  the GOD-PARTICLE mass, but lacks fuel for the generator.  He steals
  fuel from the paramilitaries.

- 2x2: On the way back to the power plant, JONAS-5 is arrested by the
  paramilitaries.  They hang him, but ELISABETH-Y saves him at the
  last minute.

- 2x2: SILJA-X releases JONAS-5 from his cage, and asks him to show
  her the GOD-PARTICLE mass.  JONAS-5 uses it to travel to 1921,
  becoming JONAS-6.  Upon leaving, ELISABETH-Y holds a gun to SILJA-X.
  SILJA-X confronts her about the GOD-PARTICLE mass.  ELISABETH says
  “they” say it’s a part of God, but she believes it is of the Devil.

*** June 27

- 2x8: ELISABETH-Y goes to the GOD-PARTICLE mass in the power plant
  and activates it.  This allows CHARLOTTE-3 to travel from 2020, just
  before the apocalypse.

*** September 23

- 3x3: MARTHA-Xb arrives from 1888.  In the ruins of the power plant,
  she finds JONAS-Zb, who must have traveled here by some means before
  the apocalypse happened in 2020.  He knows that MARTHA-Xb was in
  1888 to give the GOD-PARTICLE capsule to his younger self.  It’s not
  clear yet who ordered her to do this.

*** ??

- 3x3: JONAS-Z gives AGNES-Y a newspaper clipping of CLAUDIA-Z having
  died.  She must later give it to CLAUDIA.

- 3x3: MAGNUS-Y asks MARTHA-Xb why she acted how she did in 1888,
  giving them the fuel but then vanishing.  Apparently, 33 years later
  (in 1921) they gave her the order to do it.

- 3x4: After hugging SILJA-X, AGNES-Y enters to GOD-PARTICLE vortex,
  traveling somewhere.

- 3x4: MARTHA-Xb has made a deal with JONAS-Z.  She wants to cash in
  on his part of the agreement.  She wants to know where the origin is
  and how to destroy it.  He takes her to the Kahnwald house, saying
  that the beginning took place there, in world B.  He shows her the
  NTOEBOOK with the family diagram.  She carries the origin in her
  womb.

- 3x5: JONAS-Z tries to recruit CHARLOTTE-3 to his cause.  In one day
  they will be able to destroy the knot.

- 3x5: FRANZISKA-Y, ELISABETH-Y and CHARLOTTE-3 hug.  JONAS-Z says
  that it is time.  ELISABETH-Y and CHARLOTTE-3 enter the vortex to
  travel.

- 3x6: MARTHA-Xb is forced into a cage by SILJA-X.  JONAS-Z has the
  NOTE.  (Where did he get it? JONAS-Y burned his version in 1888.)
  She laments that she was lied to both by her elder self (who killed
  JONAS-11b) and JONAS-Z.  Her MEDALLION hangs around her neck.  The
  apocalypse must happen for “eternal darkness” to be possible.

- 3x6: MARTHA-Xb is then collected by SILJA-X and forced to undress.
  She intends to “close the gaps”.

- 3x6: MAGNUS-Y and FRANZISKA-Y are sent to November 8, 2019 in world
  B.  It is possible that they use the ORB for this, which was
  confiscated from MARTHA-Xb.

- 3x6: MARTHA-Xb is tied up, in her undergarments with the MEDALLION,
  right next to the GOD-PARTICLE mass.  MAGNUS-Y, FRANZISKA-Y,
  CHARLOTTE-4, ELISABETH-Y, SILJA-X and AGNES-Y are fulfilling their
  destinies, continuing the cycle so that this moment may exist.
  SILJA-X has traveled to 1890 wearing MARTHA-Xb’s old clothes.
  CHARLOTTE-4 and ELISABETH-Y have traveled to 2040, becoming
  CHARLOTTE-5.  JONAS-Z is expecting the end to happen now, by killing
  the origin growing in MARTHA-Xb’s womb.  He will concentrate the
  energy of both apocalypses on this point.  JONAS-Z takes her
  MEDALLION and activates the device.  MARTHA-Xb is sucked up into the
  vortex, screaming.

- 3x7: JONAS-Z does not understand that existence still continues.  At
  this point, he is met by CLAUDIA-Zb, who offers him the true solution.

- 3x8: CLAUDIA-Zb explains the nature of world Z to JONAS-Z.  Their
  conservation happens for the first time.  She tells him about the
  apocalypse loophole, and instructs him to use it to end the loop.
  She gives him the ORB.

- 3x8: Older CLAUDIA-Zb meets her somewhat younger CLAUDIA-Y self.

* B-world

** 2019

*** November 4

– 3x1: MARTHA-1b awakes in what we recognize as the Kahnwald house
  from A-world, except mirrored.  She lives there with KATHARINA-1b,
  MIKKEL-1b and MAGNUS-1b.

- 3x1: JONAS-9b arrives from the apocalypse in world A.  his guide
  there, MARTHA-Xb, uses the ORB to travel, probably to world A,
  September 21, 1888.  He goes to the Kahnwald house and takes in some
  of the differences of world B.  He later goes to the school,
  claiming to be a new student, and finds MARTHA-1b there.  After
  class he approaches her for answers, but she doesn’t know him.

- 3x1: HELGE-Zb is chanting that “it will happen again”.  CHARLOTTE-Yb
  and PETER-Yb are watching.

- 3x1: ALEKSANDER-b recruits JURGEN-b to move the BARRELS due to
  police interference.

- 3x1: Under the bridge, JONAS-9b tries again to get through to
  MARTHA-1b with some limited success.  MAGNUS-1b, BARTOSZ-1b,
  FRANZISKA-1b and KILLIAN-1b arrive and chase him away.  They go into
  the forest.  They get scared at the cave and run away, to the
  BUNKER.  There, a wormhole develops and MADS-b’s corpse drops.  They
  call the police.

- 3x1: By the Kahnwald house, JONAS-9b runs into MARTHA-Zb.  She
  explains that JONAS is never born in this world, because MIKKEL
  never traveled back.  In spite of this, which is what JONAS-9b
  wanted, this world is doomed to the same fate as world A.

*** November 5

- 3x2: MARTHA-Zb and JONAS-9b are in the headquarters of Erit Lux.  On
  the wall is Adam and Eve by Cranach.  On the floor, a complicated
  diagram of familial relationships.  She explains to him the fate of
  this world, and that the apocalypse will happen on November 8.

- 3x3: JONAS-9b’s mission in world B is to “save everyone”.

- 3x3: ULRICH-1b is convinced that someone killed MADS-b in 1986, held
  onto his belongings, and killed another person in 2019.

- 3x3: MARTHA-Zb shows JONAS-9b her MEDALLION, saying he gave it to
  her. JONAS-9b still has it in his pocket.  MARTHA-Zb asks him to
  ensure that she becomes who she is.  JONAS-9b is tired of being
  asked to do things, but he can’t deny his wants.  MARTHA-Zb
  instructs him to show MARTHA-1b her future.

- 3x3: UNKNOWN arrives in the Erit Lux headquarters, where MARTHA-Zb
  is.  He hands her: the data for the GOD-PARTICLE mass and the power
  plant master keys (taken from the power plant in world A on
  September 22, 1987), the play Ariadne and the POCKETWATCH (taken
  from elder Tannhaus in world A on September 23, 1888).  MARTHA-Zb
  didn’t tell JONAS-9b the full truth: that his MARTHA must die, so
  that everyone else can live.  He will never understand.  None of the
  objects are mirrored.  Why?

- 3x3: MARTHA-1b goes to see KILLIAN-Xb.  JONAS-9b watches from a
  distance.

- 3x3: When investigating the bunker, CHARLOTTE-Yb finds a coin on a
  string.  HELGE-Zb also has one.  When CHARLOTTE-Yb is at the church,
  questioning PETER-Yb about HELGE-Zb, he gets a call that HELGE-Zb is
  at the station, confessing.  When she gets there, she sees his coin.
  HELGE-Zb says that “it was ULRICH-b” (who attacked him in the 80s).

- 3x3: JONAS-9b earns MARTHA-1b’s attention by listing events from her
  life that he couldn’t possibly know about.  He wants to show her
  everything.  They enter the cave and travel to 2052, becoming
  JONAS-10b and MARTHA-2b.

*** November 6

- 3x4: JONAS-11b and MARTHA-3b arrive from 2052.  They have sex.  This
  is the conception of UNKNOWN.

- 3x4: In the Erit Lux headquarters, UNKNOWN is seen authoring the
  NOTEBOOK.

*** November 7

- 3x5: MARTHA-3b say her goodbyes to her mother, saying she has to go.
  Breaking into the power plant, MARTHA-3b receives the scar under her
  eye.  Realizing that he is just perpetuating the cycle, JONAS-11b
  leaves toward the caves, and MARTHA-3b follows.

- 3x5: At the Erit Lux headquarters, JONAS-11b and MARTHA-3b confront
  MARTHA-Zb.  MARTHA-Zb intends to kill JONAS-11b.  MARTHA-Yb walks
  in, joined by another MARTHA-Xb, who has a scar across her eye, and
  it looks quite fresh.  This MARTHA-Xb shoots and kills JONAS-11b.
  Before he dies, he gives her the MEDALLION.

*** November 8

- 3x6: ALEKSANDER-Yb tells BARTOSZ-Xb about his past life, and the
  murder, which he claims was an accident.  REGINA-b did not know.

- 3x6: The penny that CHARLOTTE-Yb found in the bunker, and the one
  that HELGE-Zb had are identical.  ULRICH-Yb is starting to suspect
  that HELGE-b killed MADS-b, and not the kid in the bunker (who
  ULRICH-2 does not realize is MADS-b).  When interrogating HELGE-Zb,
  he talks about time travel, and that he must stop ULRICH-Yb.  Maybe
  ULRICH-Yb is the antagonist of this world?

- 3x6: MARTHA-3b, crying, cuts her hair so that she resembles the
  older versions of herself.  She then goes to BARTOSZ-Xb to explain
  matters, who tries unsuccessfully to call ALEKSANDER-Yb.

- 3x6: HELGE-Zb goes to the cave, followed by ULRICH-Yb.  ULRICH-Yb
  leaves a voice message to CHARLOTTE-Yb.  They are observed by
  JONAS-Z and JONAS-9c.

- 3x6: Biking with BARTOSZ-Xb, MARTHA-3b is intercepted by FRANZISKA-Y
  and MAGNUS-Y, who have just arrived from 2053 in world A.  They tell
  her her elder selves have lied to her, and try to recruit her to
  their cause, to save JONAS-8 from the apocalypse in their world.
  They travel back to world A.  BARTOSZ-Xb is left behind, but later
  saved by the time traveling BARTOSZ-Yb.  It seems likely that
  BARTOSZ-Yb then instructs BARTOSZ-Xb to travel to world A, to
  prevent MARTHA-Xb from interfering with JONAS-8.

- 3x6: In an alternate timeline, MARTHA-3b is intercepted by JONAS-9c
  before being spirited away by FRANZISKA-Y and MAGNUS-Y.  He uses the
  ORB to take MARTHA-3c and himself to world A, on June 21, 1986,
  becoming JONAS-10c and MARTHA-4c.  JONAS-Z later goes to burn down
  the Erit Lux headquarters and then to use the GOD-PARTICLE mass to
  travel to meet MARTHA-Zb.

- 3x6: The apocalypse happens.

** ??

*** ??

- 3x6: At the burned down Erit Lux headquarters, MARTHA-Yb consoles
  MARTHA-Xb (who murdered JONAS-11b).  MARTHA-Xb still has her
  MEDALLION.

- 3x6: MARTHA-Xb pens the NOTE that NOAH-2 gave to JONAS-Y during the
  apocalypse to make him go save the kids.  MARTHA-Zb is of the
  opinion that it is impossible to prevent UNKNOWN’s birth, which is
  what JONAS-Z is trying to do.

- 3x6: The UNKNOWN are traveling, middle age to one world and old and
  young to the other.  They are next seen entering the volume control
  room of the power plants, causing the incidents in the summer
  of 1986.

- 3x6: In the Erit Lux machine room, we see the members of Erit Lux:
  MARTHA-Zb, MARTHA-Xb (with the scar over the eye, pregnant),
  MARTHA-Yb, BARTOSZ-Yb (who is asked to save himself), CLAUDIA-Yb
  (who is asked to guide her alternate self), EGON-Zb (who is asked to
  create his past to preserve the family tree), NOAH-Yb and NOAH-Xb
  (who must bring love, so that everything begins anew).  They travel
  off to various places.  Later, we see NOAH-Yb find ELISABETH-Xb on
  November 8, 2019 in world B, taking her to the bunker were NOAH-Xb
  is waiting.  He then leaves them alone there.  We see EGON-Zb in
  front of the cave, presumably on the same date (there is police tape
  in front), and later with HANNAH-Yb who is pregnant and bleeding.
  We see CLAUDIA-Yb with CLAUDIA-4 on September 24, 2020 in world A.
  BARTOSZ-Yb travels to save BARTOSZ-Xb from the apocalypse on
  November 8, 2020 in world B.  MARTHA-Yb is sent to 1888 in world A.

*** ??

- 3x7: At some point, CLAUDIA-5 arrives from world A to the
  burned-down Erit Lux headquarters, disguised as the now dead
  CLAUDIA-Zb.  MARTHA-b was expecting CLAUDIA-Zb to bring CLAUDIA-5
  along.  She gives her the BLUEPRINTS to give to TANNHAUS.

*** ??

- 3x7: At some point, BARTOSZ-Xb and MARTHA-Xb2 arrive from the time
  of the apocalypse in world A to the Erit Lux headquarters.
  MARTHA-Zb gives her the second scar.

- 3x8: Martha-Xb2 is set on the path to becoming EVA.  UNKNOWN is
  there, revealed to be MARTHA-Xb2’s son.  It seems his life is her
  primary motivation.  She is sent to take the life of JONAS-11b in
  front of her alternate self.

*** ??

- 3x8: JONAS-Z arrives from 2019.  He points a gun at MARTHA-Zb.  She
  expects him to kill her, and for her younger self to find the body,
  setting her on her path.  However the weapon will not fire.

** 2052

*** November 6

- 3x3: JONAS-10b and MARTHA-2b arrive from 2019.  The surroundings
  form a lifeless desert.  They are met by MARTHA-Yb, who has the scar
  across her eye, just like MARTHA-Zb.

- 3x4: The BUNKER is full of writing in Latin and German.  MARTHA-Yb
  gives MARTHA-2b the explanation she needs.  She tells them to
  prevent the opening of the BARRELS at the date of the apocalypse.
  MARTHA-Yb then says MARTHA-Zb lied to JONAS-10b, and that there is
  no way to save both worlds, and implores him to instead prevent the
  apocalypse in world B.

- 3x4: JONAS-10b and MARTHA-2b and head into the cave again.  They
  travel to 2019, becoming JONAS-11b and MARTHA-3b.  MARTHA-2b extends
  her family diagram, showing an infinity symbol (UNKNOWN) as the
  child of JONAS and MARTHA-b.  NOAH-Yb is also there.

* Z-world

** 1971

*** November 8

- 3x7: The young TANNHAUS-z family: MAREK, SONJA and CHARLOTTE-z dies
  in a car accident.

** 1974

*** ??

- 3x7: TANNHAUS-z is seen starting his work on his DEVICE in the
  BUNKER.  It has a twelve-fold dodecahedral symmetry.  The work will
  take him twelve years.

** 1986

*** June 21

- 3x7: TANNHAUS-z activates his DEVICE.
